In [1]:
import numpy as np

In [2]:
a =[1,2,3,4,5,6,7]

In [3]:
b = a

In [4]:
b

[1, 2, 3, 4, 5, 6, 7]

In [5]:
b[0]

1

In [6]:
b[0]=9

In [7]:
b

[9, 2, 3, 4, 5, 6, 7]

----

In [8]:
x =np.arange(1,6)
x

array([1, 2, 3, 4, 5])

In [9]:
y = x

In [10]:
y[0]

1

In [11]:
y[0]=8

In [12]:
y

array([8, 2, 3, 4, 5])

In [18]:
z = np.copy(x) #x dizisini kopyalayıp z değişkenine attım.

In [19]:
z

array([8, 2, 3, 4, 5])

In [20]:
z[0]=1

In [21]:
z

array([1, 2, 3, 4, 5])

In [22]:
x

array([8, 2, 3, 4, 5])