In [1]:
import numpy as np

In [5]:
a = np.array([1,2,3,4])
b = np.array([5,6,7,8])

In [6]:
np.concatenate([a,b]) #iki farlı diziyi birleştirdim.

array([1, 2, 3, 4, 5, 6, 7, 8])

X VE Y OLMAK ÜZERE İKİ TANE MATRİX DEĞİŞKENİ TANIMLADIM. VE BUNLARI BİRLEŞTİRDİM. NOT: CONCATENATE KOMUTU X VE Y DEĞİŞKENİN VERİLERİ EŞİT MİKTARDA OLDUĞU İÇİN ÇALIŞTI.EĞER EŞİTSİZLİK OLURSA ÇALIŞMAZ.

In [8]:
x = np.array(([1,2,3],[4,5,6],[7,8,9]))

In [9]:
x

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [10]:
y = np.array(([10,11,12],[13,14,15],[16,17,18]))
y

array([[10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [11]:
np.concatenate([x,y])

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [14]:
np.concatenate([x,y],axis=0)

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12],
       [13, 14, 15],
       [16, 17, 18]])

In [15]:
np.concatenate([x,y],axis=1)

array([[ 1,  2,  3, 10, 11, 12],
       [ 4,  5,  6, 13, 14, 15],
       [ 7,  8,  9, 16, 17, 18]])

In [27]:
m = np.array(([1,4,7],[10,13,16],[19,22,25]))
n = np.array(([2,5,8],[11,14,17],[20,23,26]))
z = np.array(([3,6,9],[12,15,18],[21,24,27]))
np.concatenate([m,n,z],axis=1) # axis 1'in anlamı bunları alt alta değil yan yana birleştirerek göster demek.

array([[ 1,  4,  7,  2,  5,  8,  3,  6,  9],
       [10, 13, 16, 11, 14, 17, 12, 15, 18],
       [19, 22, 25, 20, 23, 26, 21, 24, 27]])

DİZİ BOYUTU EŞİT OLMADIĞI İÇİN ÇALIŞMIYOR YANİ ÇOK DA KULLANIŞLI BİR KOMUT DEĞİL.

In [19]:
d = np.array(([1,2,3],[4,5,6]))
e = np.array(([7,8,9],[1,2,4]))
np.concatenate([d,e])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9],
       [1, 2, 4]])

In [21]:
d = np.array(([1,2,3],[4,5,6]))
e = np.array([7,8,9])
np.concatenate([d,e])

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

DEVAMI PYTHON İLE VERİ BİLİMİ 8'DE