In [1]:
import numpy as np

In [9]:
a = np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [11]:
a = np.arange(1,10).reshape(3,3)
a

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

YUKARIDAKİ KOD UZUN HALİ ALTTAKİ KOD KISA HALİ MANTIK AYNI GÖSTERİM FARKLI(a,b)

In [19]:
b = np.arange(1,10) #NOT: 0'dan başlayamaz. 1 ile 10 arasında dizi oluştur.

In [20]:
b #diziyi yazdır.

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [21]:
b.reshape(3,3) #tek boyutlu elemanı matrixe dönüştür.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [24]:
c = np.random.randint(1,10,9) #9 farklı rastgele dizi oluştur.
c

array([4, 3, 1, 8, 4, 5, 3, 5, 3])

In [25]:
c.reshape(3,3) #matrixe dönüştür.

array([[4, 3, 1],
       [8, 4, 5],
       [3, 5, 3]])

In [26]:
d = np.array((1,2,3)) #d elemanına 3 tane veriden oluşan dizi attık.

In [27]:
d.ndim #d elemanın kaç boyutlu olduğunu söylüyor.

1

In [28]:
e = d.reshape(1,3) # d elemanını 1 satır 3 sütundan oluşan matrix dönüştürdüm.

In [30]:
e

array([[1, 2, 3]])

In [49]:
e.ndim #dizi artık 2(1,3) boyutlu

2