In [1]:
liste = [1,2,3,4,5]

In [2]:
liste

[1, 2, 3, 4, 5]

In [3]:
import numpy as np

In [4]:
a = np.array([1,2,3,4,5])

In [5]:
a

array([1, 2, 3, 4, 5])

In [6]:
type(a)

numpy.ndarray

In [10]:
liste1 = [1,2,3,4,5]
liste2 = (6,7,8,9,0)

In [8]:
liste3 = np.array(liste1)

In [9]:
liste3

array([1, 2, 3, 4, 5])

In [11]:
liste4 = np.array(liste2)

In [12]:
type(liste4)

numpy.ndarray

In [14]:
for i in liste4:
    print(type(i))

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [17]:
c = np.array([1,2,3,4,5,6.9])

In [18]:
for i in c:
    print(type(i)) #hepsini int yapsaydı veri kaybı olacaktı o yüzden float değer olduğu için hepsini int'ten float'a dönüştürdü.

<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>
<class 'numpy.float64'>


In [20]:
d = np.array([1,2,3,4,5,6.9],dtype="int32")
for i in d:
    print(type(i)) #float değer olduğu için hepsini int'e çevirdim ama çok kullanılan bir yöntem değil.

<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>
<class 'numpy.int32'>


In [22]:
np.zeros(10) #bunlar hep sıfır kalır değiştirilemez.

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [23]:
np.zeros(10,dtype="int8") #şimdilik sıfır ama değişebilir. En fazla 256 değerini alabilir.

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0], dtype=int8)

In [24]:
np.ones(12)

array([1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1., 1.])

In [25]:
np.ones(12)*6

array([6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6., 6.])

In [26]:
np.full(14,7) #kaç tane ve hangi rakam olacak

array([7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7, 7])