1) Numpy kütüphanesini ekleyin.

2) ([1,2,3,4,5,6]) elemanlarından oluşan bir array oluşturun.

3) İçerisinde 6 tane 1 barındıran bir array oluşturun.

4) 0'lardan oluşan 3 satır 4 sütunlu bir array oluşturun.

5) 8'lerden oluşan 4 satır 5 sütunlu bir array oluşturun.

6) 20'den başlayarak 50'ye kadar 3'er atlamalı bir oluşturun.

7) 2,9,7,1,4,6,3 değerleinden oluşan tek boyutlu bir array oluşturun.

8) 0 ila 20 arasında aynı uzaklıkta 5 elemanlı bir array oluşturun.(linspace)

9) Normal dağılımlı 3 satır 4 sütunlu bir array oluşturun.(randn)

10) 4 elemanlı birim matris oluşturun.(eye)

11) 0-1 arası 10 adet rastgele sayı oluşturup bu sayıların en büyük ve en küçüğünü bulun.

12) Rastgele sayılardan oluşan 5 satır 4 sütunlu bir matris oluşturun.

13) "1. satırdaki tüm değerlere ulaşın.

14) "2. satırdaki 3. sütundaki elema ulaşın.

15) "3. sütundaki tüm elemanlara ulaşın.

16) for döngüsü ile 2 satır ve 3 sütundan oluşan matrisin elemanlarını alt alta yazınız.

17) 0-1 arası rastgele 6 sayı oluşturup 5 ile çarpın.

18) Array'ın sayıları toplamını bulun.

19) Array'ın medyanını bulun.

20) Array'ın standar sapmasını bulun.

In [91]:
import numpy as np

In [3]:
a = np.array([1,2,3,4,5,6])
a

array([1, 2, 3, 4, 5, 6])

In [4]:
np.ones(6)

array([1., 1., 1., 1., 1., 1.])

In [7]:
np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [94]:
#np.ones((4,5))*8 bu da kullanılır fakat alttaki daha pratik.
np.full([4,5],8)

array([[8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8],
       [8, 8, 8, 8, 8]])

In [11]:
np.arange(20,50,3)

array([20, 23, 26, 29, 32, 35, 38, 41, 44, 47])

In [60]:
b = np.array([2,9,7,1,4,6,3])
print("Dizinin elemanları :", b)
print("\nDizi kaç boyutlu :", b.ndim)

Dizinin elemanları : [2 9 7 1 4 6 3]

Dizi kaç boyutlu : 1


In [22]:
np.linspace(0,20,5)

array([ 0.,  5., 10., 15., 20.])

In [97]:
#c = np.random.randn(3,4) rand ile randn farkı randn negatif sayıda eklemesidir.
c = np.random.rand(3,4)
c

array([[0.2276193 , 0.43817155, 0.55810864, 0.33239839],
       [0.34866471, 0.47194004, 0.57908481, 0.94792556],
       [0.55191094, 0.66049182, 0.10221043, 0.74471467]])

In [34]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [98]:
d = np.random.rand(10)
print("10 rastgele sayı : ",d)
print("\nEn küçük sayı : ",d.min())
print("\nEn büyük sayı : ",d.max())

10 rastgele sayı :  [0.9555521  0.98736033 0.63175778 0.30583862 0.75863326 0.78644759
 0.53665461 0.01873072 0.05744023 0.48389673]

En küçük sayı :  0.018730722940081046

En büyük sayı :  0.9873603276702295


In [99]:
#e = np.random.randint(1,50,20).reshape(5,4) alttaki ile mantık aynı sadece gösterim farklı
e = np.random.randint(1,50,size=(5,4))
e

array([[ 4, 28, 34, 20],
       [11, 41,  2, 46],
       [15, 39, 22, 30],
       [47,  1, 49, 37],
       [44, 15, 11,  8]])

In [100]:
e[1,:]

array([11, 41,  2, 46])

In [101]:
e[2,3]

30

In [102]:
e[:,3]

array([20, 46, 30, 37,  8])

In [104]:
f = np.arange(1,7).reshape(2,3)
f

array([[1, 2, 3],
       [4, 5, 6]])

In [105]:
for i in f.flat: #flat komutu altalta sıralar.
    print(i)

1
2
3
4
5
6


In [106]:
g = np.random.rand(6)
g

array([0.10610167, 0.45873844, 0.17311534, 0.19067147, 0.06563878,
       0.50891374])

In [111]:
g*5

array([0.53050837, 2.29369219, 0.86557672, 0.95335736, 0.3281939 ,
       2.54456868])

In [112]:
g.sum()

1.5031794440497181

In [113]:
np.median(g)

0.18189340814300065

In [114]:
g.std()

0.17065231966066266