In [1]:
import numpy as np

In [2]:
a = np.random.randint(1,20,12) #başlangıç = 1, bitiş = 20, kaç tane veri = 12

In [3]:
a

array([12, 10, 16,  1,  1,  8, 14, 14,  4, 12,  4,  8])

In [7]:
np.split(a,[5])

[array([12, 10, 16,  1,  1]), array([ 8, 14, 14,  4, 12,  4,  8])]

In [9]:
np.split(a,[2,5]) #ilk 2 veri 1. array dizisi sonraki 3,4 ve 5. sıradaki veri 2. array dizisi geri kalanı 3. array dizisidir.

[array([12, 10]), array([16,  1,  1]), array([ 8, 14, 14,  4, 12,  4,  8])]

In [10]:
 np.split(a,[2,5,8])

[array([12, 10]),
 array([16,  1,  1]),
 array([ 8, 14, 14]),
 array([ 4, 12,  4,  8])]

In [13]:
x,y,z,q = np.split(a,[2,5,8])
print("1. ve 2. sıradaki veri : ", x)
print("3., 4. ve 5. sıradaki veri : ", y)
print("6., 7. ve 8. sıradaki veri : ", z)
print("9., 10., 11. ve 12. sıradaki veri : ", q)

1. ve 2. sıradaki veri :  [12 10]
3., 4. ve 5. sıradaki veri :  [16  1  1]
6., 7. ve 8. sıradaki veri :  [ 8 14 14]
9., 10., 11. ve 12. sıradaki veri :  [ 4 12  4  8]


In [28]:
b = np.random.randint(0,12,12).reshape(3,4)
b

array([[ 7,  8,  4,  6],
       [ 1, 10,  9,  7],
       [ 7,  4, 10,  0]])

In [29]:
np.split(b,[1])

[array([[7, 8, 4, 6]]),
 array([[ 1, 10,  9,  7],
        [ 7,  4, 10,  0]])]

In [30]:
np.split(b,[1,2])

[array([[7, 8, 4, 6]]), array([[ 1, 10,  9,  7]]), array([[ 7,  4, 10,  0]])]

In [31]:
np.split(b,[2])

[array([[ 7,  8,  4,  6],
        [ 1, 10,  9,  7]]),
 array([[ 7,  4, 10,  0]])]

In [32]:
np.hsplit(b,[1]) #hsplit komutu ile sütun olarak bölüyor. düz split yazınca satır olarak bölüyor.

[array([[7],
        [1],
        [7]]),
 array([[ 8,  4,  6],
        [10,  9,  7],
        [ 4, 10,  0]])]