In [1]:
import numpy as np

In [3]:
np.arange(0,10) #tek tek elle yazmak yerine arange ile otomatik iki sayı arasındaki veriyi yazdırabiliriz.

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [4]:
np.arange(0,30,2) #başlangıç = 0, bitiş = 30, kaçar kaçar artsın = 2

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28])

In [5]:
np.arange(0,3,0.5)

array([0. , 0.5, 1. , 1.5, 2. , 2.5])

In [10]:
np.linspace(0,100,5) #başlangıç = 0, bitiş = 100, kaç eşit parçaya bölsün = 5

array([  0.,  25.,  50.,  75., 100.])

In [11]:
np.random.rand(5) #0'dan 5'e kadar rastgele sayı oluştur.

array([0.78470947, 0.65755934, 0.11352312, 0.61755063, 0.04760459])

In [12]:
np.random.rand(2,3) #rastgele değerlerden 2'ye 3 matrix oluştur.

array([[0.14739598, 0.75901523, 0.78406981],
       [0.67304081, 0.25367226, 0.67871546]])

In [13]:
np.random.normal(0,1,(3,3)) #0 ile 1 arasında 3'e 3'lük matrix oluştur.

array([[-0.02631775,  0.29101457, -0.30862849],
       [ 0.78307945,  1.07206861,  0.21276257],
       [-1.79177506, -0.60420176,  1.6646139 ]])

In [15]:
np.random.normal(10,3,(3,3)) #ortalaması 10 standart sapma 3 olan 3x3'lük matrix oluştur.

array([[10.7205482 , 19.13800294, 14.72295885],
       [14.70328511,  9.65943975, 10.10806426],
       [ 9.45540752,  8.94643612, 11.81857612]])

In [16]:
np.random.randint(0,10) #tam sayılardan 0 ile 10 arasında rastgele sayı oluştur.

7

In [17]:
np.random.randint(10) #yukarıdaki(0,10) ile (10) ifadesinin gösteriminin mantığı aynı

6

In [18]:
np.random.randint(0,10,5) #0'dan başla 10'a kadar 5 farklı sayı oluştur.

array([4, 5, 6, 7, 2])

In [19]:
np.random.randint(0,10,(4,2)) #başlangıç = 0, bitiş = 10, matrix = 4x2 rastgele tam sayı oluştur.

array([[9, 4],
       [2, 7],
       [2, 2],
       [0, 4]])

In [20]:
np.random.randn(3,4) #3 satır ve 4 sütundan oluşan bir matris oluşturur.
#Bu matrisin her bir elemanı, standart normal dağılıma sahip rastgele sayılarla doldurulur.
#Standart normal dağılım, ortalama değeri 0 ve varyansı 1 olan bir dağılımdır.
#Yani, her eleman, bu dağılıma göre rastgele seçilir.

array([[-1.30906535,  0.41958689,  0.38198239, -1.05445779],
       [-0.15005638, -0.43499202, -1.55164154, -1.44807041],
       [-0.16104657,  0.22448966, -0.29468521,  0.45628577]])

In [21]:
np.eye(8) # çapraz bir şekilde sol üstten sağ alta kadar 1 ifadesi geri kalanı 0 değerini döndürür.

array([[1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1.]])