In [29]:
import numpy as np

In [30]:
np.array([(1,2,3),(4,5,6)]) #iki boyutlu dizi matrix

array([[1, 2, 3],
       [4, 5, 6]])

In [31]:
np.array([(1,2,3),(4,5,6),(7,8,9)])

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [32]:
np.ones((3,3)) #1'ler 3 satır ve 3 sütundan oluşan matrix

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [35]:
np.ones((2,4)) #1'lerden oluşan 2 satır ve 4 sütundan matrix

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])