In [2]:
import numpy as np

In [11]:
a = np.random.randint(1,30,10)
a

array([27, 16,  6, 20, 15, 15, 12,  9, 26, 20])

In [12]:
max(a)

27

In [13]:
min(a)

6

In [14]:
np.argmax(a) #en büyük sayı kaçıncı indekste olduğunu gösterir.

0

In [15]:
np.argmin(a) #en küçük sayı kaçıncı indekste olduğunu gösterir.

2

In [16]:
sum(a) #dizideki verilerin toplamı

166

---

In [48]:
b = np.random.randint(1,30,[5,4])
b

array([[22,  8, 25,  8],
       [26, 12, 18,  7],
       [ 8, 10,  2,  1],
       [15,  5,  5, 25],
       [28, 26,  6,  9]])

In [49]:
sum(b) #sütunları baz alarak toplama işlemi gerçekleştirdim.

array([99, 61, 56, 50])

In [50]:
b.sum(axis = 0) #sütunları baz alarak toplama işlemi gerçekleştirdim.

array([99, 61, 56, 50])

In [51]:
 b.sum(axis=1) #satırları baz alarak toplama işlemi gerçekleştirdim.

array([63, 63, 21, 50, 69])

In [52]:
b.sum().sum() #tüm satır ve sütunların toplamını yaptırdım.

266

In [53]:
b.mean() #verilerin ortalamasını aldırdım.

13.3

In [54]:
np.median(b) #verilerin ortadaki 2 sayıyı seçip toplayıp ve 2 ye böler.

9.5

In [55]:
b.std() #standart sapmasını verir.

8.769834662067467