In [2]:
import numpy as np

In [11]:
x = np.array(([1,2,3],[4,5,6]))

In [12]:
y = np.array([7,8,9])

In [13]:
y

array([7, 8, 9])

In [14]:
x

array([[1, 2, 3],
       [4, 5, 6]])

In [15]:
np.vstack([x,y]) #boyutları eşit olmayan dizileri concatenate ile birleştirilemediği için dizileri vstack komutu ile birleştirdik.

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

ALT ALTA DEĞİLDE YANYANA NASIL EKLENİYOR?

In [16]:
np.hstack([x,y]) #y değişkenindeki dizinin 2.satırın 4,5,6 hücresi boş olduğu için birleştiremiyor.

ValueError: all the input arrays must have same number of dimensions, but the array at index 0 has 2 dimension(s) and the array at index 1 has 1 dimension(s)

In [18]:
x = np.array(([1,2,3],[4,5,6]))
y = np.array(([7,8],[9,0]))
np.hstack([x,y]) # çalışmasının nedeni y dizisindeki veri 2 tane olduğu için eşitledi.

array([[1, 2, 3, 7, 8],
       [4, 5, 6, 9, 0]])