In [1]:
import numpy as np

In [3]:
a = np.random.randint(20,size=10) #20'ye kadar olacak şekilde 10 farklı veri dizisi oluştur.

In [4]:
a

array([ 5, 15,  3,  1,  6, 15,  4, 17, 12, 13])

In [5]:
a[0] #a'nn 0. indeksini göster.

5

In [6]:
a[9] #a'nn 9. indeksini göster.

13

In [7]:
a[0]=9 #a'nn 0. indeksini 9 rakamı ile değiştir.

In [8]:
a[0] #a'nn 0. indeksini göster.

9

In [9]:
a #a dizisini göster.

array([ 9, 15,  3,  1,  6, 15,  4, 17, 12, 13])

-----

In [10]:
b = np.random.randint(12,size=(3,4))

In [11]:
b

array([[ 3,  0,  4, 10],
       [ 0,  7,  6,  3],
       [ 9, 11,  4,  5]])

In [13]:
b[0,0]

3

In [15]:
b[2,3]

5

----

In [16]:
c = np.random.randint(20,size=10)

In [17]:
c

array([16, 12, 14,  7, 19,  7,  4, 17,  0, 10])

In [18]:
c[0:2] # c dizisindeki sadece 0 ve 1. indeksi getirir.

array([16, 12])

In [19]:
c[2:8] #c dizisindeki sadece 2,3,4,5,6 ve 7. indeksi getirir.

array([14,  7, 19,  7,  4, 17])

In [20]:
c[:4] #c dizisinin baştan 3. indekse kadar olanı getirir.

array([16, 12, 14,  7])

In [23]:
c[1::2] #1. indeksten sona kadar 2 atlayarak sonuçları getirir.(getirdiği indeksler:1,3,5,7,9)

array([12,  7,  7, 17, 10])

In [24]:
c[::2] #0. indeksten sona kadar 2 atlayarak sonuçları getirir.(getirdiği indeksler:0,2,4,6,8)

array([16, 14, 19,  4,  0])

In [25]:
c[4:] #4.indeksten başlar sona kadar olan indeksleri getirir.

array([19,  7,  4, 17,  0, 10])

In [28]:
c[::]

array([16, 12, 14,  7, 19,  7,  4, 17,  0, 10])

c[::] gösterimi ile sadece c yazmanın mantığı aynı

------

In [29]:
d = np.random.randint(20,size=(5,4))
d

array([[11,  4, 13, 10],
       [ 8,  7,  1,  6],
       [ 5, 19,  3,  4],
       [12, 14,  0,  7],
       [ 9, 10,  7,  4]])

In [30]:
d[2,3] #2.satır 3.sütundaki veriyi getirir.

4

In [31]:
d[4,2]

7

In [32]:
d[1:] #1. satırdan en son satıra kadar ve sütunları getirir.

array([[ 8,  7,  1,  6],
       [ 5, 19,  3,  4],
       [12, 14,  0,  7],
       [ 9, 10,  7,  4]])

1:4,2:3 VİRGÜLE KADAR OLAN İLK KISIM SATIRLARI VİRGÜLDEN SONRAKİ KISIM SÜTUNLARI İFADE EDER.

In [33]:
d[1,:] #1.satır ve tüm sütunları getirir.

array([8, 7, 1, 6])

In [35]:
d[2,:3] #2. satır 2.sütuna kadar olan verileri getirir.

array([ 5, 19,  3])

In [36]:
d[:,2] #2.sütun ve tüm satırlardaki verileri getirir.

array([13,  1,  3,  0,  7])

In [37]:
d[3:,:3] #3. satırdan son satıra kadar olanı getir ve sütunlardanda 2.sütuna kadar olanı getir.

array([[12, 14,  0],
       [ 9, 10,  7]])

In [38]:
d

array([[11,  4, 13, 10],
       [ 8,  7,  1,  6],
       [ 5, 19,  3,  4],
       [12, 14,  0,  7],
       [ 9, 10,  7,  4]])

In [41]:
d[1:3,2:] #1.satırdan 2'ye kadar, 2.sütundan sona kadar olan verileri getirir.

array([[1, 6],
       [3, 4]])

In [43]:
d[3:,1:3]

array([[14,  0],
       [10,  7]])

In [46]:
d[2:3,1:2]

array([[19]])

In [48]:
d[2,1]

19