In [1]:
import numpy as np

In [2]:
a = np.random.randint(0,15,5)

In [3]:
a

array([ 8, 13,  1,  6,  4])

In [4]:
np.sort(a) # sort komutu ile küçüken büyüğe sıraladım.

array([ 1,  4,  6,  8, 13])

In [5]:
a #göründüğü üzere bir değişkene atmadığımız için hafızaya atmadı.

array([ 8, 13,  1,  6,  4])

In [6]:
a = np.sort(a)

In [7]:
a

array([ 1,  4,  6,  8, 13])

--------------------------------------------

In [28]:
b = np.random.randint(0,20,5)

In [29]:
b

array([ 4,  2,  2, 11,  4])

In [30]:
c = np.argsort(b)

In [31]:
c

array([1, 2, 0, 4, 3], dtype=int64)

In [32]:
np.sort(b)

array([ 2,  2,  4,  4, 11])

ARGSHORT VERİNİN KAÇINCI İNDEX'TE OLDUĞUNU GÖSTERİR. SHORT KOMUTU İLE VERİYİ KÜÇÜKTEN BÜYÜĞE SIRALATIP KAÇINCI İNDEKSTE OLDUĞUNU KONTROL ETTİM. YANİ

2'NİN BULUNDUĞU İNDEKS 1
2'NİN BULUNDUĞU İNDEKS 2
4'ÜN BULUNDUĞU İNDEKS 0
4'ÜN BULUNDUĞU İNDEKS 4
11'İN BULUNDUĞU İNDEKS 3

ARRAY(4,2,2,11,4) İNDEKS OLARAK (0,1,2,3,4)

BU ŞEKİLDE KONTROL ETMİŞ OLDUM.