In [1]:
import numpy as np

In [3]:
a = np.arange(1,5)
a

array([1, 2, 3, 4])

In [4]:
a+5 # a dizisindeki verileri 5 ile toplattım.

array([6, 7, 8, 9])

In [5]:
a*2 # a dizisindeki verileri 2 ile çarptırdım.

array([2, 4, 6, 8])

In [33]:
b = np.arange(5,9)
b

array([5, 6, 7, 8])

In [8]:
a+b # a ve b dizisi verilerini toplattım.

array([ 6,  8, 10, 12])

In [10]:
c = np.arange(1,4)
c

array([1, 2, 3])

In [12]:
d = np.arange(1,10).reshape(3,3)
d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [13]:
d+c

array([[ 2,  4,  6],
       [ 5,  7,  9],
       [ 8, 10, 12]])

In [14]:
e = np.arange(1,4).reshape(3,1)
e

array([[1],
       [2],
       [3]])

In [15]:
c+e

array([[2, 3, 4],
       [3, 4, 5],
       [4, 5, 6]])

In [20]:
f = np.arange(1,11)
f

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [30]:
g = np.arange(1,11).reshape(10,1)
g

array([[ 1],
       [ 2],
       [ 3],
       [ 4],
       [ 5],
       [ 6],
       [ 7],
       [ 8],
       [ 9],
       [10]])

In [32]:
h=f*g
h

array([[  1,   2,   3,   4,   5,   6,   7,   8,   9,  10],
       [  2,   4,   6,   8,  10,  12,  14,  16,  18,  20],
       [  3,   6,   9,  12,  15,  18,  21,  24,  27,  30],
       [  4,   8,  12,  16,  20,  24,  28,  32,  36,  40],
       [  5,  10,  15,  20,  25,  30,  35,  40,  45,  50],
       [  6,  12,  18,  24,  30,  36,  42,  48,  54,  60],
       [  7,  14,  21,  28,  35,  42,  49,  56,  63,  70],
       [  8,  16,  24,  32,  40,  48,  56,  64,  72,  80],
       [  9,  18,  27,  36,  45,  54,  63,  72,  81,  90],
       [ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100]])