In [2]:
import numpy as np

In [3]:
a = np.arange(1,8)
a

array([1, 2, 3, 4, 5, 6, 7])

In [4]:
a>5 #5'den büyükleri True, küçükleri False değeri döndürür.

array([False, False, False, False, False,  True,  True])

In [5]:
a>=5 #5'den büyükleri ve 5'e eşit olanları True, küçükleri False değeri döndürür.

array([False, False, False, False,  True,  True,  True])

In [6]:
a<=5 #5'den küçükleri ve 5'e eşit olanları True, büyükleri False değeri döndürür.

array([ True,  True,  True,  True,  True, False, False])

In [7]:
np.sum(a>=5) #5'e eşit ve büyük olanların kaç tane olduğunu söyler.

3

In [9]:
np.sum((a>2) & (a<6)) #2'den büyük ve 6'dan küçük verilerin kaç tane olduğunu söyler.

3

In [10]:
np.sum(a>2) & np.sum(a<6) #2'den büyük ve 6'dan küçük olanların kaç tane olduğunu bul ve toplayıp ekrana yaz.

5

In [13]:
b = np.random.randint(1,10,(3,3))
b

array([[6, 7, 1],
       [1, 9, 8],
       [6, 6, 4]])

In [14]:
b > 5

array([[ True,  True, False],
       [False,  True,  True],
       [ True,  True, False]])

In [16]:
np.sum(b>5)

6

In [20]:
np.sum(b>5,axis=1) #satır satır ve bakar 5'den büyük kaç tane olduğunu söyler.

array([2, 2, 2])

In [21]:
np.sum(b>5,axis=0) #sütun sütun bakar ve 5'den büyük kaç tane olduğunu söyler.

array([2, 3, 1])

---

In [22]:
c = np.random.randint(1,10,(4,3))
c

array([[6, 8, 8],
       [8, 8, 6],
       [2, 1, 3],
       [5, 2, 2]])

In [24]:
np.all(c>0) #all komutu ile verilerin hepsi 0'dan büyükse True değerini döndürür.

True

In [26]:
np.all(c>3) #all komutu ile verilerin hepsi 3'den büyük mü olduğna bakar fakat küçük değer varsa False değerini döndürür.

False

In [25]:
np.any(c>3) #any komutu ile verilerin herhangi biri 3'den büyükse True değerini döndürür.

True